### ISSUE TITLE
Is there a way to do a PATCH of an entity?

### ISSUE THREAD

**Issue by grrenier** [remult/remult#229] opened 2023-08-26 13:47 UTC
Hello,
I was trying to update a single attribute of an entity but I just see update or save and they send all the attributes of the object in the payload. For example it would be nice to have something like: 

`remult.repo(MyEntity).patch(id, {isActive: true});`

Thank you

**Comment by noam-honig** [comment] 2023-08-26 19:59
I think that update will do exactly that:
```ts
remult.repo(MyEnity).update(id, {isActive:true})
```

Another option is change a member and send the update:
```ts
let myEntity = remult.repo(MyEntity).findFirst()
myEntity.isActive=true
remult.repo(MyEntity).save(myEntity)
```

**Comment by grrenier** [comment] 2023-08-27 02:29
I tried and it works, just the HTTP method is a PUT instead of a PATCH, but it does the job.

**Comment by groszdaniel** [comment] 2023-09-13 02:27
@noam-honig Is update supposed to keep all fields that are not specified intact? It seems to me that in some circumstances other fields get overwritten (perhaps primitive types and/or allowNull?). Indeed, in the PUT network request some other fields (not specified in the second parameter of update) are specified with null values.

**Comment by noam-honig** [comment] 2023-09-13 04:37
@groszdaniel yes - unspecified fields shoud stay intact. If not, it's a bug and I would like to fix it.
Can you give me some information on how to reproduce it?

**Comment by groszdaniel** [comment] 2023-09-17 04:31
@noam-honig I made a simple example based on the React starter project: https://github.com/groszdaniel/remult-update-bug

One entity, two integer fields, each button is supposed to increment one without touching the other. Instead, when one is incremented, the other becomes 0. In the network request, you can see that a 0 is sent for the unspecified field. (Not in the example, but strings are set to an empty string, for instance.) The allowNull option doesn't actually matter.

If you fix this, I suggest also updating the documentation to make it clear that it's allowed to only specify some fields. Currently, all examples specify unchanged fields like this:
`repo.update(id, { ...foo, field: value })`
That's why it wasn't clear to me if it was a bug that other fields are zeroed, or intended behavior. The `...foo` is currently necessary, but it should be superfluous if the bug is fixed.

**Comment by noam-honig** [comment] 2023-09-17 05:01
Thanks. I'm out of town, will look at it tomorrow

**Comment by noam-honig** [comment] 2023-09-18 07:14
Sorry about that, this issue was already fixed in version:
https://github.com/remult/remult/releases/tag/v0.22.4

My bad for not updating the starter kit - will do that now

**Closed** 2024-09-16 04:08 UTC
